<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>TDSProtocol</RootNamespace>
    <AssemblyName>TDSProtocol</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TDSProtocolTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.0" />
  </ItemGroup>

</Project>
